name:   testWorkflows
on: push
jobs:
    npm-install:
        name:   npm-build工作
        runs-on: ubuntu-latest
        steps:
            - name: 读取仓库内容
              uses: actions/checkout@v4
            - name: 查看目录
              run: pwd
            - name: 查看npm版本
              run: npm --version
            - name: 查看node版本
              run: node --version
            - name: 安装依赖
              run: npm install
            - name: 项目打包
              run: npm run build
    # npm-test: