on: push
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - run: pwd
            - run: ls
            - run: echo "Hello, World!"
    job2:
        runs-on: windows-latest
        steps:
            - run: node --version